const frases = [
    "Eres suficiente tal y como eres, sin necesidad de cambiar nada.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Tu autenticidad es tu mayor fortaleza, nunca la pierdas.",
    "Eres capaz de lograr todo lo que te propongas.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "La belleza comienza en el momento en que decides ser tú misma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres suficiente tal y como eres.",
    "El mundo necesita tu luz y tu amor.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres capaz de superar cualquier obstáculo que se presente en tu vida.",
    "El amor propio es el cimiento de todas tus relaciones.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres una obra maestra en constante evolución.",
    "El amor propio no es vanidad, es cordura.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Cada momento de autocompasión es un acto de amor propio.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres suficiente, exactamente como eres.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres una persona increíblemente valiosa y especial.",
    "El amor propio es la fuente de toda sanación.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Ama cada parte de ti, incluso aquellas que consideras defectos.",
    "Eres capaz de superar cualquier desafío con gracia y fortaleza.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para crecer y florecer.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Confía en tu intuición y sigue tu corazón.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "La autenticidad es tu superpoder; nunca dejes de ser tú misma.",
    "El amor propio es el primer paso hacia la verdadera felicidad.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "El mundo necesita tu luz y tu amor.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres una obra maestra en constante evolución.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres suficiente, exactamente como eres.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "El amor propio es la fuente de toda sanación.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres capaz de lograr todo lo que te propongas.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "El amor propio no es vanidad, es cordura.",
    "Eres una obra de arte en constante creación.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Tu amor propio es un acto de valentía y fuerza.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres una obra de arte en constante evolución.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres suficiente tal y como eres, sin necesidad de cambiar nada.",
    "Tu autenticidad es tu mayor fortaleza, nunca la pierdas.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "La belleza comienza en el momento en que decides ser tú misma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres suficiente tal y como eres.",
    "El mundo necesita tu luz y tu amor.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres capaz de superar cualquier obstáculo que se presente en tu vida.",
    "El amor propio es el cimiento de todas tus relaciones.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres una obra maestra en constante evolución.",
    "El amor propio no es vanidad, es cordura.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Cada momento de autocompasión es un acto de amor propio.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres suficiente, exactamente como eres.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres una persona increíblemente valiosa y especial.",
    "El amor propio es la fuente de toda sanación.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Ama cada parte de ti, incluso aquellas que consideras defectos.",
    "Eres capaz de superar cualquier desafío con gracia y fortaleza.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para crecer y florecer.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Confía en tu intuición y sigue tu corazón.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "La autenticidad es tu superpoder; nunca dejes de ser tú misma.",
    "El amor propio es el primer paso hacia la verdadera felicidad.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "El mundo necesita tu luz y tu amor.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres una obra maestra en constante evolución.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres suficiente, exactamente como eres.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "El amor propio es la fuente de toda sanación.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres capaz de lograr todo lo que te propongas.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "El amor propio no es vanidad, es cordura.",
    "Eres una obra de arte en constante creación.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Tu amor propio es un acto de valentía y fuerza.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres una obra de arte en constante evolución.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres suficiente tal y como eres, sin necesidad de cambiar nada.",
    "Tu autenticidad es tu mayor fortaleza, nunca la pierdas.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "La belleza comienza en el momento en que decides ser tú misma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres suficiente tal y como eres.",
    "El mundo necesita tu luz y tu amor.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres capaz de superar cualquier obstáculo que se presente en tu vida.",
    "El amor propio es el cimiento de todas tus relaciones.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres una obra maestra en constante evolución.",
    "El amor propio no es vanidad, es cordura.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Cada momento de autocompasión es un acto de amor propio.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres suficiente, exactamente como eres.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres una persona increíblemente valiosa y especial.",
    "El amor propio es la fuente de toda sanación.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Ama cada parte de ti, incluso aquellas que consideras defectos.",
    "Eres capaz de superar cualquier desafío con gracia y fortaleza.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para crecer y florecer.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Confía en tu intuición y sigue tu corazón.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "La autenticidad es tu superpoder; nunca dejes de ser tú misma.",
    "El amor propio es el primer paso hacia la verdadera felicidad.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "El mundo necesita tu luz y tu amor.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres una obra maestra en constante evolución.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres suficiente tal y como eres, sin necesidad de cambiar nada.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Tu autenticidad es tu mayor fortaleza, nunca la pierdas.",
    "Eres capaz de lograr todo lo que te propongas.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "La belleza comienza en el momento en que decides ser tú misma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres suficiente tal y como eres.",
    "El mundo necesita tu luz y tu amor.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres capaz de superar cualquier obstáculo que se presente en tu vida.",
    "El amor propio es el cimiento de todas tus relaciones.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres una obra maestra en constante evolución.",
    "El amor propio no es vanidad, es cordura.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Cada momento de autocompasión es un acto de amor propio.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres suficiente, exactamente como eres.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres una persona increíblemente valiosa y especial.",
    "El amor propio es la fuente de toda sanación.",
    "Tu voz merece ser escuchada y tus ideas compartidas.",
    "Ama cada parte de ti, incluso aquellas que consideras defectos.",
    "Eres capaz de superar cualquier desafío con gracia y fortaleza.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para crecer y florecer.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Confía en tu intuición y sigue tu corazón.",
    "El amor que te das a ti misma es el amor más importante.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "Eres digna de todo el amor y la felicidad del mundo.",
    "La autenticidad es tu superpoder; nunca dejes de ser tú misma.",
    "El amor propio es el primer paso hacia la verdadera felicidad.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de amarte a ti misma.",
    "Tu valor no depende de la opinión de los demás.",
    "Eres una obra de arte en constante creación.",
    "Cada paso que das es un paso hacia tu mejor versión.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Ama tus cicatrices, porque cuentan la historia de tu fortaleza.",
    "Tu felicidad comienza cuando te aceptas tal y como eres.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "El mundo necesita tu luz y tu amor.",
    "Eres una flor que florece en su propio tiempo y espacio.",
    "Tu autenticidad te hace verdaderamente especial.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "Confía en tu proceso y en el camino que estás recorriendo.",
    "Eres una obra maestra en constante evolución.",
    "Ama y respétate a ti misma, porque eres digna de todo el amor del mundo.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres capaz de cosas maravillosas, solo necesitas creer en ti misma.",
    "Tu fortaleza interior es tu mayor aliado.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres una persona increíblemente talentosa y creativa.",
    "Nunca dejes que nadie te haga sentir menos de lo que eres.",
    "Eres suficiente, exactamente como eres.",
    "El amor propio es la clave para una vida plena y feliz.",
    "Tu autenticidad te hace verdaderamente hermosa.",
    "Eres más fuerte de lo que piensas y más valiente de lo que crees.",
    "Cada día es una nueva oportunidad para crecer y aprender.",
    "Tu valor no se mide por lo que haces, sino por quién eres.",
    "Eres la autora de tu propia historia, escribe con amor y pasión.",
    "Ama y cuida de ti misma como lo harías con alguien que amas profundamente.",
    "El amor propio es la fuente de toda sanación.",
    "Eres una persona única y maravillosa, nunca lo olvides.",
    "Eres capaz de lograr todo lo que te propongas.",
    "Tu capacidad para amar comienza contigo misma.",
    "Confía en tu intuición y sigue tu corazón.",
    "Eres una luz brillante en el mundo, sigue iluminando.",
    "Nunca subestimes el poder de tus sueños y tu determinación.",
    "El amor propio no es vanidad, es cordura.",
    "Eres una obra de arte en constante creación.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Tu fortaleza radica en tu capacidad de ser vulnerable.",
    "Eres suficiente tal y como eres, y mereces todo lo bueno que la vida tiene para ofrecerte.",
    "El mundo necesita tu luz y tu amor.",
    "Cada día es una nueva oportunidad para abrazar tu autenticidad.",
    "Eres digna de todo el amor y la felicidad que el mundo puede ofrecer.",
    "Tu amor propio es un acto de valentía y fuerza.",
    "Eres una fuente de inspiración para todos los que te rodean.",
    "El crecimiento personal es un viaje sin fin, disfrútalo.",
    "Eres una obra de arte en constante evolución.",
    "Eres la dueña de tu destino y la capitana de tu alma.",
    "Eres suficiente tal y como eres, sin necesidad de cambiar nada."
];



function obtenerFraseDelDia() {
    const hoy = new Date();
    const diaDelAno = Math.floor((hoy - new Date(hoy.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
    return frases[diaDelAno % frases.length];
}

document.addEventListener("DOMContentLoaded", function() {
    const contenedorFrase = document.getElementById("frase-del-dia");
    if (contenedorFrase) {
        contenedorFrase.textContent = obtenerFraseDelDia();
    }
});
